# Generated by Django 2.0 on 2020-06-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2aclab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-created_time']},
        ),
    ]
