# Generated by Django 2.0 on 2020-06-04 12:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2aclab', '0002_auto_20200603_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_art', to='s2aclab.ArticleType'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
