# Generated by Django 2.0 on 2020-06-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2aclab', '0003_auto_20200604_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
