# Generated by Django 2.0 on 2020-06-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s2aclab', '0004_articles_read_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='read_count',
        ),
        migrations.AddField(
            model_name='readnum',
            name='artilce',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='s2aclab.Articles'),
        ),
    ]
