# Generated by Django 2.0 on 2020-06-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s2aclab', '0006_auto_20200605_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='article',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
